include: package:lints/recommended.yaml

linter:
  rules:
    # Errors
    avoid_print: true
    avoid_slow_async_io: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    hash_and_equals: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    non_constant_identifier_names: true
    null_closures: true
    package_api_docs: true
    package_prefixed_library_names: true
    overridden_fields: true
    prefer_const_constructors_in_immutables: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    sort_constructors_first: true
    type_annotate_public_apis: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    valid_regexps: true

    # Warnings
    avoid_as: true
    avoid_empty_else: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_annotating_with_dynamic: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    avoid_void_async: true
    camel_case_extensions: true
    cascade_invocations: true
    curly_braces_in_flow_control_structures: true
    diagnostic_describe_all_properties: true
    only_throw_errors: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true

    # Style
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    always_specify_types: true
    annotate_overrides: true
    avoid_escaping_inner_quotes: true
    avoid_positional_boolean_parameters: true
